# Copyright Intel Corporation

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: dashboard-input
data:
  dashboard.json: |-
{{ .Files.Get "dashboard_pdd.json" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: evam-config-input
data:
  config.json: |-
{{ .Files.Get "evam_config.json" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: vis-str-config-input
data:
  config.json: |-
{{ .Files.Get "viz_str_config.json" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: vis-config-input
data:
  config.json: |-
{{ .Files.Get "viz_config.json" | indent 4 }}