#
# Apache v2 license
# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.mqttbroker.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: ia-mqtt-broker
  ports:
    - name: broker-port
      port: {{ .Values.config.mqttbroker.int.port }}
      targetPort: {{ .Values.config.mqttbroker.int.port }}
      nodePort: {{ .Values.config.mqttbroker.ext.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ia-mqtt-broker
  name: deployment-mqtt-broker
  namespace: {{ .Values.namespace }}

spec:
  selector:
    matchLabels:
      app: ia-mqtt-broker
  template:
    metadata:
      labels:
        app: ia-mqtt-broker
    spec:
      containers:
      - name: ia-mqtt-broker
        image: eclipse-mosquitto:2.0.21
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        securityContext:
          runAsUser: {{ $.Values.env.TIMESERIES_UID }}
          runAsGroup: {{ $.Values.env.TIMESERIES_UID }}
          readOnlyRootFilesystem: true 
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        {{ if eq .Values.env.SECURE_MODE true}}
        - name: mosquitto-conf
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
        - name: certs
          mountPath: /run/secrets/ca_certificate.pem
          subPath: ca_certificate.pem
        - name: certs
          mountPath: /run/secrets/mqtt-broker_Server_server_certificate.pem
          subPath: mqtt-broker_Server_server_certificate.pem
        - name: certs
          mountPath: /run/secrets/mqtt-broker_Server_server_key.pem
          subPath: mqtt-broker_Server_server_key.pem
        {{- else }}
        - name: mosquitto-dev-conf
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
        {{ end }}

      volumes:
        - name: mosquitto-conf
          configMap:
            name: mosquitto-conf
        - name: mosquitto-dev-conf
          configMap:
            name: mosquitto-dev-conf
      {{ if eq .Values.env.SECURE_MODE true}}
        - name: certs
          secret:
            secretName: ts-certs
            items:
            - key: ca_certificate.pem
              path: ca_certificate.pem
            - key: mqtt-broker_Server_server_certificate.pem
              path: mqtt-broker_Server_server_certificate.pem
            - key: mqtt-broker_Server_server_key.pem
              path: mqtt-broker_Server_server_key.pem
      {{ end }}